server:
  port: 8080

all-db:
  datasource:
    maxActive: 20
    maxIdle: 20
    minIdle: 15
    initialSize: 15

sharded-db:
  - shardID: localhost:5432/postgres
    datasource:
      jdbcUrl: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
  - shardID: localhost:5432/shard2
    datasource:
      jdbcUrl: jdbc:postgresql://localhost:5432/shard2
      username: postgres
      password: postgres

spring:
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true

logging:
  #  config: classpath:logback-bluewhale-json-appender.xml
  config: classpath:logback-bluewhale-local.xml
  level:
    root: INFO
    org.flywaydb.core.internal.dbsupport.SqlScript: DEBUG
    app.narvi: DEBUG
    org.springframework: INFO

